---
# This playbook contains the plays to add the RPM Fusion repo

- name: Download Repository RPM (EPEL)
  action: command rpm -Uvh {{ epel_rpm_url }}

- name: Download Repository RPM (RPM Fusion Free and Non-Free)
  action: command yum localinstall --nogpgcheck {{ free_rpm_url }} {{ nonfree_rpm_url }}
