---
# This playbook deploys the whole application stack in this site

- name: Apply common configuration 
  hosts: all
  sudo: true
 
  vars:
    rpm_folder: repo-rpm
    rpm_path: /home/vagrant/{{ rpm_folder }}
    rpm_url: http://packages.sw.be/rpmforge-release
    rpm: rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
    
  roles:
    - common
#    - web
#    - db
